version: 2

models:

    - name: sales
      description: >
        Primary key is orders_id and
        products_id concatenation
      
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"            
            
      columns:
          - name: orders_id
            description: identifier for the order number
            tests : 
            - not_null 

          - name: products_id
            tests : 
            - not_null 

          - name: qty

          - name: turnover
            tests : 
            - not_null 

          - name: purchase_cost
            tests : 
            - not_null 

          - name: margin